export const RED_CHANNEL_INPUT = 'RED_CHANNEL_INPUT';
export const GREEN_CHANNEL_INPUT = 'GREEN_CHANNEL_INPUT';
export const BLUE_CHANNEL_INPUT = 'BLUE_CHANNEL_INPUT';
export const RGB_VALUES = 'RGB_VALUES';
export const UPDATE_NAME = 'UPDATE_NAME';
export const GET_NAMES = 'GET_NAMES';
export const GET_SELECTED_NAME = 'GET_SELECTED_NAME';
